source 'https://github.com/rorodriguez116/AmphibianPods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Portal_Example' do
  pod 'Portal', :path => '../'

  target 'Portal_Tests' do
    inherit! :search_paths

    
  end
end
